### PR TITLE
Replaced Resizesensor with ResizeObserver

### PR DESCRIPTION
**Pull request by Alucard17**
hey, I am using this library in my Nuxt js Project, I have replaced ResizeSensor dependency with [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) which has 83.7 % support in [Can I use](https://caniuse.com/#feat=resizeobserver).

For the older browsers, we can polyfill it.

### CODE REVIEW

**Comment by blixhavn** [comment]
@Alucard17 I just noticed, your PR breaks a couple of the unit tests. I've had a look at it, but couldn't immediately figure out what the problem was. I'd look further, but as I'm currently in paternity leave I don't have a lot of long, uninterrupted periods of time in which to investigate the problem. Could you please have a look? The tests can be run by simply opening the tests/index.hml file in your favorite browser.

**Comment by Alucard17** [comment]
Okay I'll take a look

**Comment by bacloud22** [comment]
@Alucard17 I opened one issue that might be relative to resize observer.
Could you please help ?

I basically want to set width to `width: max-content !important;` because otherwise the sidebar takes the whole space of the page width and other elements are not clickable any-more !

Can you provide an option to deactivate width recalculations ??
I don't understand why width has to be recalculated on viewport resize, I can understand for height but not width really.

**Comment by bacloud22** [comment]
I can play on z-index of sidebar and other elements, but then many things might be unpredictable (bootstrap elements everywhere)

**Pull request merged**
